# Generated by Django 5.1.6 on 2025-02-24 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afforestation_status',
            fields=[
                ('afforestation_id', models.AutoField(primary_key=True, serialize=False)),
                ('afforestation_name', models.CharField(max_length=255)),
                ('afforestation_size', models.IntegerField(default=1)),
                ('author_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_level', models.IntegerField(default=0)),
                ('skill_script', models.FileField(blank=True, null=True, upload_to='skills/')),
                ('skill_description', models.TextField()),
                ('author_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('tree_age', models.IntegerField(default=0)),
                ('tree_rank', models.IntegerField(default=1)),
                ('grows_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.afforestation_status')),
            ],
        ),
    ]
