# Generated by Django 5.1.6 on 2025-03-07 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerUp',
            fields=[
                ('power_up_id', models.AutoField(primary_key=True, serialize=False)),
                ('power_up_name', models.CharField(max_length=255)),
                ('power_up_type', models.CharField(max_length=255)),
                ('power_up_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_type', models.CharField(max_length=255)),
                ('skill_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Afforestation_status',
            fields=[
                ('Afforestation_id', models.AutoField(primary_key=True, serialize=False)),
                ('Afforestation_name', models.CharField(max_length=255)),
                ('Afforestation_rank', models.IntegerField(default=1)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('stats_od', models.AutoField(primary_key=True, serialize=False)),
                ('max_break_tree', models.IntegerField(default=0)),
                ('break_trees', models.IntegerField(default=0)),
                ('status_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_game.status')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('tree_age', models.IntegerField(default=0)),
                ('tree_rank', models.IntegerField(default=1)),
                ('tree_completed', models.IntegerField(default=0)),
                ('afforestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.afforestation_status')),
            ],
        ),
        migrations.CreateModel(
            name='UserPowerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_up_level', models.IntegerField(default=0)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('power_up_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.powerup')),
                ('status_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.status')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_level', models.IntegerField(default=0)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('skills_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.skills')),
                ('status_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.status')),
            ],
        ),
    ]
