# Generated by Django 5.1.6 on 2025-02-26 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerUp',
            fields=[
                ('power_up_id', models.AutoField(primary_key=True, serialize=False)),
                ('power_up_name', models.CharField(max_length=255)),
                ('power_up_level', models.IntegerField(default=1)),
                ('power_up_type', models.CharField(max_length=255)),
                ('power_up_description', models.TextField()),
                ('author_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
